BuildingSync/schema

BuildingSync.xsd, CHANGELOG.md
* Rename CommercialFacility to Facility and add enum to specify the facility type
* Break out ceiling system from RoofCeilingSystem
=> Facilities update

BuildingSync.xsd, examples/PrimarySchoolCRB1.xml
* Major cleanup of the Primary School file.
=> Fix primary school

Gemfile, Rakefile, circle.yml, test/validation_test.rb
* Use minitest for testing. Right now the tests are crude, but the framework now exists.
=> move tests to minitest

BuildingSync.xsd, examples/PrimarySchoolCRB1.xml
=> case facility

BuildingSync.xsd, CHANGELOG.md, examples/HighLevel.xml, examples/PrimarySchoolCRB1.xml
=> New example file

BuildingSync.xsd, CHANGELOG.md, examples/HighLevel.xml, examples/PrimarySchoolCRB1.xml
The reports list of package of measures should have been pluralized.
=> Pluralize measureids

BuildingSync.xsd
Additions:
* Conditioned floors above grade
* Unconditioned floors above grade
* Conditioned floors below grade
* Unconditioned floors below grade
* BAS (boolean)
* Landmark status (boolean)
* Benchmark year
* Number of facilities
=> PNNL Requests, part 1

BuildingSync.xsd, CHANGELOG.md, examples/PrimarySchoolCRB1.xml, examples/ashrae211.xml
Small number of additional elements and revised enumerations based on
update to BEDES in September 2016.
=> Updates based on revisions in BEDES Version 2.0

BuildingSync.xsd, examples/HighLevel.xml
Both @fieldkm and I have made changes here, so this one is on you, @nllong. I'd like to do the change to spaces rather than tabs after this PR gets merged, so let's hold of on changes for a bit. Don't delete the branch after the merge.
=> Pnnl Requests, Part 2

BuildingSync.xsd, examples/HighLevel.xml
Some PNNL-requested work: above- and below-grade wall areas, overall WWR, slab R and U, user-def field in Boiler, "none" enum to ChilledWaterResetControl, added InsulationCondition as a simpleType
=> Pnnl requests

BuildingSync.xsd, examples/PrimarySchoolCRB1.xml
Add an equipment condition element to the schema and use it one of the example files.
=> Equipment Condition

BuildingSync.xsd, examples/PrimarySchoolCRB1.xml
This should replace #29, which had an additional empty commit. The original PR was good to go except for that commit, so this just needs to be checked over (then we can close #29).
=> Add COP to SHW units

BuildingSync.xsd, examples/PrimarySchoolCRB1.xml
Add a burner quantity and control type. We still need to verify the control type enum values, but I'll go ahead and make the pull request.
=> Burner Additions

BuildingSync.xsd, examples/PrimarySchoolCRB1.xml
This adds a annual peak reduction element in two places in the schema and adds it into one of the test files.
=> Add Annual Peak Reduction Element

examples/PrimarySchoolCRB1.xml
@fieldkm Oops, we merged too fast, the example file needed a name change too. This fixes that.
=> Fix example file failure

BuildingSync.xsd
Update the version number, so far I've only found the one spot.
=> Update Version for Release

BuildingSync.xsd, Rakefile, docs/release_instructions.md, examples/ASHRAE 211 Export.xml, examples/CMS Woodlawn Campus.xml, examples/Golden Test File.xml, examples/Multi-Facility Shared Systems.xml, examples/MultitenantBySubsections.xml, examples/NIST Gaithersburg Campus.xml, examples/Norfolk Federal Building.xml, examples/Reference Building - Primary Schoool.xml, examples/Richmond Federal Building.xml, spec/validation_spec.rb
* Add in the golden test file that meets requirements per PNNL
* Add test to ensure the XSD and example XMLs do not contain tabs
* Add rake task to remove tabs
=> Add Golden Test File

BuildingSync.xsd, examples/Golden Test File.xml, proposals/2018/Add UBID.md
See the proposals/2018/add ubid.md
=> Proposal to add UBID

Gemfile, examples/LL87.xml
This file is a copy of the Golden Test File that will be expanded as needed to support the ll87 use case.
=> Add LL87 Test File

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Add IDs to Report and Qualification.md
See proposals/2019/Add IDs to Report and Qualification.md below.
=> Add ID to Report and Qualification

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Qualifications List V2.md
See proposals/2019/Qualifications List V2.md.
=> Auditor Qualification Enums

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Linear Fluorescent Enumeration.md
See proposals/2019/Linear Fluorescent Enumeration.md
=> Update Linear Fluorescent Enumerations

BuildingSync.xsd, examples/BuildingSync Website Valid Schema.xml, examples/LL87.xml, proposals/2019/Add Plant Fields.md
Added YearInstalled to CondenserPlant, CoolingPlant, and HeatingPlant
=> adding YearInstalled to Plant paths

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Terminal Unit Enumerations.md
see proposals/2019/Terminal Unit Enumerations.md
=> New TerminalUnit Enumerations

BuildingSync.xsd, examples/ASHRAE 211 Export.xml, examples/CMS Woodlawn Campus.xml, examples/LL87.xml, examples/NIST Gaithersburg Campus.xml, examples/Norfolk Federal Building.xml, examples/Reference Building - Primary Schoool.xml, examples/Richmond Federal Building.xml, proposals/2019/Audit Date Enumerations.md
See proposals/2019/Audit Date Enumerations.md
=> Multiple Audit Dates in Report

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Consolidate Misc Gas Loads.md
See proposals/2019/Consolidate Misc Gas Loads.md
=> Move Miscellaneous Gas Loads under ProcessLoad

BuildingSync.xsd, examples/ASHRAE 211 Export.xml, examples/Golden Test File.xml, examples/LL87.xml, examples/Multi-Facility Shared Systems.xml, examples/NIST Gaithersburg Campus.xml, examples/Norfolk Federal Building.xml, examples/Reference Building - Primary Schoool.xml, proposals/2019/Rename OnSite to Onsite.md
See proposals/2019/Rename OnSite to Onsite.md
=> OnSite to Onsite

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Package of Measures ID.md
proposals/2019/Package of Measures ID.md
=> Package of Measures ID

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Plant and Source Location.md
see proposals/2019/Plant and Source Location.md
=> Location Elements on Plants/Sources

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Add Scenario Notes.md
Adding ScenarioNotes element to Scenario.
=> Scenario notes

BuildingSync.xsd, examples/ASHRAE 211 Export.xml, examples/BuildingSync Website Invalid Schema.xml, proposals/2019/Ballast Type Enums.md
**THIS IS A BREAKING CHANGE**
Changed enums on Ballast Type element:
remove "Electronic"
added: "Standard Electronic" and "Premium Electronic"
=> Ballast type enumeration values

BuildingSync.json, BuildingSync.xsd, proposals/2019/Add None to ControlTechnology.md
See `proposals/2019/Add None to ControlTechnology.md` for details.
=> Add "None" value to <auc:ControlTechnology> enumeration

BuildingSync.xsd
=> Fix coolroof name

examples/LL87.xml
@supriyagoel -- here is an updated example with an indirect water heater from a boiler. Let me know if this isn't what you were looking for.
=> Indirect Water Heater Example

BuildingSync.xsd, proposals/2019/Add to Measure Scale of Application.md
See `proposals/2019/Add to Measure Scale of Application.md` for details.
=> MeasureScaleOfApplication - Add Enumerations

BuildingSync.json, BuildingSync.xsd, examples/BuildingSync Website Invalid Schema.xml, examples/Reference Building - Primary School.xml, proposals/2019/Add Efficiency Units Enums.md
See `proposals/2019/Add Efficiency Units Enums.md` for details.
=> Add EfficiencyUnits enumerations

BuildingSync.json, BuildingSync.xsd, proposals/2019/Add FuelTypes enums for Fuel oil no 5 and 6.md
See `proposals/2019/Add FuelTypes enums for Fuel oil no 5 and 6.md` for details.
=> Add FuelTypes enumerations for "Fuel oil no 5 and 6"

BuildingSync.json, BuildingSync.xsd, proposals/2019/Add ElectricResistance to HeatingSourceType.md
See `proposals/2019/Add ElectricResistance to HeatingSourceType.md` for details.
=> Add ElectricResistance to HeatingSourceType

BuildingSync.xsd, proposals/2019/Rename GasElec to GasElectric.md
See `proposals/2019/Rename GasElec to GasElectric.md` for details.
=> Rename ProcessGasElecLoadType element

BuildingSync.json, BuildingSync.xsd, proposals/2019/Add CondensingOperation enums.md
See `proposals/2019/Add CondensingOperation enums.md` for details.
=> CondensingOperation - Add Enumerations

BuildingSync.json, BuildingSync.xsd, examples/ASHRAE 211 Export.xml, examples/Reference Building - Primary School.xml
Replace the term "TimeStamp" with "Timestamp".
=> Modify capitalization of term "Timestamp"

BuildingSync.xsd, proposals/2019/Add DraftBoundary enums.md
See `proposals/2019/Add DraftBoundary enums.md` for details.
=> DraftBoundary - Add Enumerations

BuildingSync.xsd, proposals/2019/Add AuditorQualificationType enumerations.md
See `proposals/2019/Add AuditorQualificationType enumerations.md` for details.
=> Add AuditorQualificationType enumerations

BuildingSync.xsd, examples/BuildingSync Website Invalid Schema.xml, examples/Reference Building - Primary School.xml, proposals/2019/Pluralize LinkedDeliveryID.md
See `proposals/2019/Pluralize LinkedDeliveryID.md` for details.
=> Pluralize LinkedDeliveryID

BuildingSync.xsd, proposals/2019/Add Gas Engine to Chiller Compressor Driver.md
=> Add Gas Engine Enumeration to Chiller Compressor Driver

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Add PercentLeasedByOwner to Building.md
=> Add Percent Leased by Owner to Building

BuildingSync.xsd, proposals/2019/Add ExteriorFloorSystemType.md
See `proposals/2019/Add ExteriorFloorSystemType.md` for details.
=> Add ExteriorFloorSystemType Element

BuildingSync.xsd, proposals/2019/Replicate Site Elements in Building Element.md
See `proposals/2019/Replicate Site Elements in Building Element.md` for details.
=> Replicate Site Elements in Building Element

BuildingSync.xsd, proposals/2019/Harmonize Tightness and TightnessFitCondition elements.md
See `proposals/2019/Harmonize Tightness and TightnessFitCondition elements.md` for details.
=> Harmonize Tightness and TightnessFitCondition elements

BuildingSync.xsd, examples/AT_example_property_report_25.xml, examples/AT_example_report_332.xml
Terms with the prefix "Year Of ..." should conform to BEDES capitalization rules.
=> Fix capitalization - Prefix 'Yearof' should be 'YearOf'

BuildingSync.xsd
Should be constrained to "auc:OtherType" element.
=> Add missing @type attribute to 'Other' element in schema for 'DeliveryType' element.

BuildingSync.xsd, examples/AT_example_property_report_25.xml, examples/AT_example_report_332.xml, proposals/2019/Pluralize ControlSystemType element in Plants.md
See `proposals/2019/Pluralize ControlSystemType element in Plants.md` for details.
=> Pluralize `auc:ControlSystemType` element for plants

BuildingSync.xsd, proposals/2019/Add MeasureName to TechnologyCategory for BuildingEnvelopeModifications.md
See `proposals/2019/Add MeasureName to TechnologyCategory for BuildingEnvelopeModifications.md` for details.
=> Add <auc:MeasureName> enumeration to <auc:TechnologyCategory> element for 'BuildingEnvelopeModifications'.

.gitignore, BuildingSync.xsd, examples/AT_example_property_report_25.xml, examples/AT_example_report_332.xml
Addressing issue https://github.com/BuildingSync/schema/issues/135
=> Bound percentages

BuildingSync.xsd, examples/Reference Building - Primary School.xml, proposals/2019/Modify DaylightingIlluminanceSetpoint units.md
See `proposals/2019/Modify DaylightingIlluminanceSetpoint units.md` for details.
Closes #153
=> Modify DaylightingIlluminanceSetpoint units

BuildingSync.xsd
=> Fix spelling errors in documentation for SectionType element

BuildingSync.xsd, examples/AT_example_property_report_25.xml, examples/AT_example_report_332.xml, src/data_dictionary.rb
=> Validate format of telephone number

examples/AT_example_NYC_audit_report_property.xml, examples/AT_example_SF_audit_report.xml
=> run bundle exec rake remove_tabs on updated ATT files

BuildingSync.xsd, proposals/2020/Add Energy Cost Index.md
=> Add EnergyCostIndex element

examples/AT_BRICR_audit_report.xml
Example BRICR Audit Report imported from Example SF Report. Lighting data has been edited to include number of fixtures, and Energy Savings Opportunities data has been edited to include additional field inputs and an additional package with 3 measures.
=> Add BRICR example generated by Audit Template

BuildingSync.xsd
For consistency with:
- `auc:FlatRate`
- `auc:TimeOfUseRate`
=> update tiered rate to include demand rate start and end dates

BuildingSync.xsd, proposals/2020/Add Energy Use Elements.md
Also see these [slides](https://docs.google.com/presentation/d/1-JSfXUhc68JUhGdDLkGgSCkLt_xSW1uMVEV872pEgm0/edit?usp=sharing) on how we plan on having BuildingSync model Energy Use and EUI
=> feat(proposals): add energy use elements proposal

BuildingSync.xsd, CHANGELOG.md
- Bumps all version references to 2.2.0-pr1, and adds it as a enum to version attribute.
=> feat(schema): add 2.2.0-pr1 version

BuildingSync.xsd
See https://github.com/BuildingSync/TestSuite/issues/30
=> Add capacity to condenser plant types

BuildingSync.xsd, proposals/2020/Add Interval Duration.md
Also see https://github.com/BuildingSync/TestSuite/issues/33
=> Add IntervalDuration and IntervalDurationUnits to TimeSeries

CHANGELOG.md, LICENSE.md, README.md, spec/validation_spec.rb, src/change_log.rb, src/data_dictionary.rb
Update README to be more helpful.
=> update readme and changelog

.github/workflows/publish.yml, docs/release_instructions.md
=> docs: add notes for making pre-releases

BuildingSync.xsd, proposals/2021/Delete Add or replace cooling tower.md
See proposal.
Reference issue #330
=> Remove redundant "Add or replace cooling tower"

BuildingSync.xsd, proposals/2021/Deprecate Capacity and CapacityUnits in Delivery.md
=> Deprecate Capacity and CapacityUnits in Delivery

BuildingSync.xsd, examples/AT_example_NYC_audit_report_property.xml, examples/AT_example_SF_audit_report.xml, examples/Reference Building - Primary School.xml, examples/Single_building_gbxml_externalreference_geometry.xml, proposals/2021/Deprecate OutputCapacity.md
=> Deprecate OutputCapacity for HeatingSource and HeatingPlant types

docs/notebooks/bsync_examples/Small-Office-Level-1.ipynb
Update the urls to the selection tool -- now use case validator.
=> fix selection tool urls

BuildingSync.xsd, proposals/2021/Add PRMS.md
Create proposal "Add PRMS.md"
Implement in schema
Resolves #381
=> Add PRMS in eGRIDRegionCode

docs/notebooks/bsync_examples/Small-Office-Level-1.ipynb, docs/notebooks/bsync_examples/example1.xml
The version of Python used for running the Jupyter notebook was a bit out of date.
* Update version of python for Jupyter notebook
* save the example XML file to the repo
n/a
n/a
=> Update Jupyter notebook

BuildingSync.xsd, proposals/2021/Add MaximumOutsideAirFlowRate.md
See proposal. 
Address first part of #296.
=> Add MaximumOutsideAirFlowRate

CHANGELOG.md, README.md, docs/notebooks/bsync_examples/Small-Office-Level-1.ipynb, docs/notebooks/bsync_examples/example1.xml, docs/release_instructions.md, proposals/2020/BuildingSync Versioning.md, proposals/2021/Add MaximumOutsideAirFlowRate.md, proposals/2021/Add eGRIDSubregionCodes.md, spec/validation_spec.rb, src/change_log.rb
These updates were manually copied from develop before develop-v3 becomes new develop!
=> manually pull in changes from develop

spec/validation_spec.rb
=> gbxml not geojson

.github/workflows/CI_Labels.yml, src/change_log.rb
BSync is starting to use PRs for tracking changes to the schema instead of issues.
- Changelog now uses PRs to determine breaking/non-breaking changes to schema as well as categories affected
- Require PRs to have one of the labels "Non-schema Change" if it doesn't affect the schema
- Requires PRs affecting the schema to include a scope label (e.g. "Schema: Systems")
- Run the changelog script, things should work as expected
New changelog format
=> chore: update ci label reqs and changelog generation

.github/workflows/CI_Labels.yml
I am bad at remembering variable names
=> ci: fix labels CI

examples/ASHRAE 211 Export.xml, examples/AT_example_AS_conversion_audit_report.xml, examples/AT_example_NYC_audit_report_property.xml, examples/AT_example_SF_audit_report.xml, examples/BuildingSync Website Invalid Schema.xml, examples/BuildingSync Website Valid Schema.xml, examples/CMS Woodlawn Campus.xml, examples/DC GSA Headquarters.xml, examples/Golden Test File.xml, examples/LL87.xml, examples/Multi-Facility Shared Systems.xml, examples/Multi_building_gbxml_externalreference_geometry.xml, examples/MultitenantBySubsections.xml, examples/NIST Gaithersburg Campus.xml, examples/Norfolk Federal Building.xml, examples/Reference Building - Primary School.xml, examples/Richmond Federal Building.xml, examples/Single_building_gbxml_externalreference_geometry.xml
Not sure how we missed this branch, but this is needed.
=> Update example version reference to 2.4

proposals/2021/Add ACH75 and ACH100 to AirInfiltrationValueUnits.md, proposals/2021/Add AirInfiltrationTestPressureBoundary.md, proposals/2021/Add AirInfiltrationTestPressureDifferential.md, proposals/2021/Add AirSideEconomizerCondition.md, proposals/2021/Add Podium.md, proposals/2021/Add Unitized.md, proposals/2021/Add YearInstalled to FenestrationSystemType.md
N/A
This PR adds proposals related to the addition of the city of Washington, D.C., [Building Energy Performance Standards (BEPS)](https://doee.dc.gov/service/building-energy-performance-standards-beps) template to the Audit Template tool.
N/A
N/A
N/A
=> Proposals for DC BEPS template

.gitignore, docs/notebooks/example1-with-sensors.xml
Use BuildingSync to store sensor data. This could be in the form of an M&V 
* Uses the existing schema (no updates) to store wind and temperature timeseries data.
* Just an example, review and opine.
https://github.com/BuildingSync/project-tracker/issues/90
=> Add example with sensor data in notebook directory

docs/notebooks/bsync_examples/Small-Office-Level-1.ipynb, docs/notebooks/bsync_examples/example1.xml, docs/notebooks/poetry.lock, docs/notebooks/pyproject.toml
Doesn't look like the example1 file was updated with the GHG. 
* Update example1.xml
* Point bsyncpy to develop branch through github, until release that is.
* bump version of jupyter server for security
* poetry install
* poetry run jupyter lab
* step through the entire small office notebook
n/a
=> update example file and point to develop of bsyncpy

docs/notebooks/poetry.lock
Update the dependencies. This supersedes #452.
=> Update dependency lock file

examples/AT_example_AS_conversion_audit_report.xml, examples/AT_example_NYC_audit_report_property.xml, examples/AT_example_SF_audit_report.xml
N/A
Updates the 3 example files for Audit Template tool.
N/A
N/A
N/A
=> Update Audit Template examples

examples/BuildingEQ-1.0.0.xml
Building EQ Example XML
Adding Building EQ Example
Adding Building EQ Example
Run Building EQ Example
N/A
=> Building EQ Example XML

BuildingSync.xsd, proposals/2023/Add Measures for Data Center Energy Conservation Improvements.md
Measures requested by city of Denver, CO, during development of new audit report template in the Audit Template tool.
Adds new enumerations to the `auc:MeasureName` child element of the `auc:DataCenterImprovements` element.
N/A
N/A
N/A
=> Proposal to add measures for data center energy conservation improvements

BuildingSync.xsd, proposals/2023/Add CondenserType.md
=> Add CondenserType

BuildingSync.xsd, CHANGELOG.md
Prepare for release of BuildingSync v2.5
=> Build: prep 2.5 release

CHANGELOG.md
=> Build: prep 2.5 release update CHANGELOG.md

docs/notebooks/bsync_examples/Primary-School-Levels1-2.md, docs/notebooks/bsync_examples/Reference-PrimarySchool-L100-Audit.xml, docs/notebooks/bsync_examples/Reference-PrimarySchool-L200-Audit.xml, docs/notebooks/bsync_examples/Small-Office-Level-1.md, docs/notebooks/bsync_examples/Small-Office-Level-2.md, docs/notebooks/bsync_examples/example-smalloffice-level1.xml, docs/notebooks/bsync_examples/example-smalloffice-level2.xml, docs/notebooks/example-with-emissions.xml, docs/notebooks/pyproject.toml, examples/ASHRAE 211 Export.xml, examples/AT_example_AS_conversion_audit_report.xml, examples/AT_example_NYC_audit_report_property.xml, examples/AT_example_SF_audit_report.xml, examples/BuildingEQ-1.0.0.xml, examples/BuildingSync Website Invalid Schema.xml, examples/BuildingSync Website Valid Schema.xml, examples/CMS Woodlawn Campus.xml, examples/DC GSA Headquarters.xml, examples/Golden Test File.xml, examples/LL87.xml, examples/Multi-Facility Shared Systems.xml, examples/Multi_building_gbxml_externalreference_geometry.xml, examples/MultitenantBySubsections.xml, examples/NIST Gaithersburg Campus.xml, examples/Norfolk Federal Building.xml, examples/Reference Building - Primary School.xml, examples/Richmond Federal Building.xml, examples/Single_building_gbxml_externalreference_geometry.xml
Update examples to 2.5 as it's released
=> Update examples to 2.5

BuildingSync.xsd, proposals/2024/Add AuditCycleStartDate and AuditCycleEndDate.md
=> Add AuditCycleStartDate and AuditCycleEndDate
