BuildingSync.xsd, examples/PrimarySchoolCRB1.xml, examples/ashrae211.xml, examples/cts.xml
This will make HeatingPlantType into a separate complexType. Previously, both cooling plant and condenser plant had complex types, but heating plant did not. Unfortunately, the diffs are very hard to review, so I've tried to make as few changes as possible.
* Renamed "CoolingPlantType" to "CoolingPlant"
* Renamed "CoolingPlantTypeType" to "CoolingPlantType"
* Made "HeatingPlantType" a separate complexType
We shouldn't make any further system changes until after this is merged to hopefully manage the diff issue.
=> Change Heating Plant Type

BuildingSync.xsd, examples/PrimarySchoolCRB1.xml, examples/ashrae211.xml
This PR moves the utility element out of the resource use element and up to a place where multiple resource use elements can refer to it. This was an early PNNL request that we held off on making because it is a breaking change. Any files using the previous approach will no longer work.
=> Move Utility and Use References

BuildingSync.xsd, docs/release_instructions.md
xs3p documentation generation was failing due to the double dash in the annotations (--MM-DD). This removes the double dash and just makes the annotation (MM-DD).
=> Remove Double Dash in Annotations

BuildingSync.xsd, examples/DC GSA Headquarters.xml, examples/Reference Building - Primary Schoool.xml, proposals/2018/Harmonize_PremisesAffected_and_LinkedPremises.md
=> Proposal to harmonize definitions of `PremisesAffected` and `LinkedPremises`

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Add ID to AirInfiltrationSystem.md, proposals/2019/Add PlugLoadType enums.md, proposals/2019/Add UDF to PackageOfMeasures.md, proposals/2019/OccupancyClassification.md, proposals/2019/OtherEnergyGenerationTechnology.md
1. <auc:AirInfiltrationSystem> does not have @ID attribute.
2. <auc:PackageOfMeasures> element does not have <auc:UserDefinedFields> child element.
3. <auc:OtherEnergyGenerationTechnology> does not have “Reciprocating engine” value.
4. <auc:OccupancyClassification> enumeration does not have “Trading floor” or “TV studio” values.
5. <auc:PlugLoadType> enumeration does not have “Broadcast antenna”, “Kitchen equipment” and “Times Square sign” values.
All changes have examples in LL87.xml example file except for #4.
=> AirInfiltrationSystem ID, UDF on Package of Measures, enums on GenTech, OccClass, and PlugLoad

BuildingSync.xsd, examples/LL87.xml, examples/Reference Building - Primary Schoool.xml, proposals/2019/Ventilation.md
see proposals/2019/Ventilation.md
=> VentilationType Enum and VentilationControlMethods

BuildingSync.xsd, examples/LL87.xml, proposals/2019/Make FanBased Optional.md
This PR make FanBased optional which is a simple non-breaking change. The LL87 example file has been updated to demonstrate how to specify zone-based radiant systems (hot water and electrical).
=> FanBased Optional

BuildingSync.xsd, examples/LL87.xml
Fixed enums on SimulationCompletionStatus to represent status of simulation (whether the simulation was run or not) as well as the success of the run (Finished = finished successfully; Failed = finished but with errors)
=> fixing enums for SimulationCompletionStatus

BuildingSync.json, BuildingSync.xsd, proposals/2019/Add PrimaryFuel to HeatingPlantType and CoolingPlantType.md
See `proposals/2019/Add PrimaryFuel to HeatingPlantType and CoolingPlantType.md` for details.
=> Add <auc:PrimaryFuel> Element to Plants

BuildingSync.xsd, Rakefile, examples/ASHRAE 211 Export.xml, examples/LL87.xml, examples/Reference Building - Primary School.xml, proposals/2019/Controls.md, spec/validation_spec.rb
There are two proposals for refactoring the concept of controls in BSync. The options are in the LightingSystem and named Controls_1 and Controls_2. Make sure to review the proposal as it contains initial mappings.
It is best to checkout this branch and review it in a schema editor.
=> Controls refactor

BuildingSync.json, BuildingSync.xsd
In the list of enumerations for the `auc:OccupancyClassification` element, the trailing whitespace in the term "Laboratory " [sic] is removed.
=> Remove trailing whitespace from "Laboratory " [sic]

BuildingSync.xsd, proposals/2019/Add FuelTypes enums for Fuel oil no 5 light and heavy.md
See `proposals/2019/Add FuelTypes enums for Fuel oil no 5 light and heavy.md` for details.
=> Add FuelType enumerations

BuildingSync.xsd, examples/BuildingSync Website Invalid Schema.xml
When `BuildingSync.xsd` is converted to Ruby using the `xsd2ruby.rb` script from soap4r, the class that corresponds to the "Pneumatic" element is not created because there is no `<xs:simpleType>` or `<xs:complexType>` element in the definition (which soap4r appears to need).
=> Add <xs:complexType> child element to definition of "Pneumatic" element

BuildingSync.xsd, proposals/2019/Pluralize PrimaryHVACControlSystemType.md
See `proposals/2019/Pluralize PrimaryHVACControlSystemType.md` for details.
=> Pluralize and rename PrimaryHVACControlSystemType Element to HVACControlSystemType

BuildingSync.xsd
This resolves a bug in XML generation using Soap4R-autogenerated code.
Specifically, the "minOccurs" constraint causes the XML generator to always write a `auc:AllResourceTotals` element, even if it does not contain any `auc:AllResourceTotal` child elements, resulting in a schema validation error.
This is/was the only occurrence of `minOccurs="1"` in the XSD file.
=> Remove `minOccurs="1"` constraint for `auc:AllResourceTotal` element

BuildingSync.xsd, proposals/2019/Add BenchmarkValue element.md
See `proposals/2019/Add BenchmarkValue element.md` for details.
=> Add BenchmarkValue element

BuildingSync.xsd, proposals/2019/Add LinkedPremises to Benchmark.md
See `proposals/2019/Add LinkedPremises to Benchmark.md` for details.
Fixes Option 2 of #152
=> Add LinkedPremises child element to Benchmark element.

BuildingSync.xsd
Validate format of `<auc:PostalCode>` and `<auc:PostalCodePlus4>` elements.
=> Validate format of postal codes.

BuildingSync.xsd
ASHRAE 211 5.3.4.d refers to two OccupantQuantity definitions:
- Design occupancy
- Normal occupancy
There previously did not appear to be an enumeration in line with 'Normal occupancy', so this PR adds that.  Also adds documentation so that users understand exactly which enumerations to use.
=> update OccupantQuantityType enumerations with definitions

BuildingSync.xsd, CHANGELOG.md
simple update - no change in XML document structure
=> pull rate elements out as distinct element types to reduce redundancy

BuildingSync.xsd
Allow documents to have a `auc:ReheatSource` of None in `auc:Delivery`
=> Add None enum to ReheatSource

BuildingSync.xsd
Allow documents to have a `auc:AirSideEconomizerType` of None in `auc:Delivery`
=> Add None enum to AirSideEconomizerType

BuildingSync.xsd
This is to match the same enum added for AirSideEconomizer in #229
=> Add None enum to WaterSideEconomizerType

BuildingSync.xsd
See https://github.com/BuildingSync/TestSuite/issues/31
This change starts the deprecation of auc:OutputCapacity
=> Change OutputCapacity for HeatingSource and HeatingPlant types

BuildingSync.xsd
STD 211 6.2.1.2.b requires "Total area of the fenestration". BuildingSync already has OverallWindowToWallRatio, but not OverallDoorToWallRatio.
=> Add OverallDoorToWallRatio to Building

BuildingSync.xsd
It would be nice to have these IDs for identifying utility types: https://openei.org/wiki/List_of_United_States_Utility_Companies_and_Aliases#cite_note-1
=> Add EIA ID to Utility

BuildingSync.xsd, proposals/2020/Add Peak Type.md
Also see https://github.com/BuildingSync/TestSuite/issues/35
=> Add PeakType to TimeSeries

BuildingSync.xsd, proposals/2020/Resource Use Submetering.md
Also see https://github.com/BuildingSync/TestSuite/issues/36
=> Add MeterID and ParentResourceUseID to ResourceUse

docs/developer_resources.md
This creates a doc for developer resources which specifies a format for writing commit messages and branch names.
=> docs: add notes on git naming conventions

BuildingSync.xsd
Per discussion here https://github.com/BuildingSync/TestSuite/pull/37#discussion_r508725106
> It doesn't make sense to have Delivery capacity when the linked systems (fan, heating, cooling) have capacities of their own.
=> docs(schema): add deprecation warning for Delivery Capacity

BuildingSync.xsd
We should use FanInstalledFlowRate instead of InstalledFlowRate to match the naming for pumps, PumpInstalledFlowRate
This marks the beginning of the deprecation of InstalledFlowRate.
=> refactor(schema): add choice for FanInstalledFlowRate

BuildingSync.xsd
When running `bundle exec rake remove_tabs` the <p> section of an annotation is updated.
* ensures that `bundle exec rake remove_tabs` generates the correctly formatted BuildingSync.xsd
n/a
n/a
=> <p> formatting in XSD

.github/workflows/publish.yml, docs/release_instructions.md, docs/versioning.md
We added semantic versioning to bsync
Add the notes from the semver proposal to the official docs for better accessibility.
Also I noticed an error in the publishing github workflow which should be fixed now.
=> docs: add versioning documentation

BuildingSync.xsd, proposals/2021/Break Insulate attic hatch stair box into two.md, proposals/2021/Break Repair leaks seal ducts into two.md
Using `/` with spaces around to connect two phrases might cause ambiguity. Our proposal is to break the option into two to avoid using `/`. See proposal for more details.
1. 'Repair leaks / seal ducts' -> 'Repair leaks in ducts' and 'Seal ducts'
2. 'Insulate attic hatch / stair box' -> 'Insulate attic hatch' and 'Insulate attic stair box'
Resolved #332
=> Address issue using `/` with spaces

BuildingSync.xsd, proposals/2021/Deprecate MORE in eGRIDRegionCode.md
=> Deprecate MORE in eGRIDRegionCode

BuildingSync.xsd, proposals/2021/Delete Add heat recovery.md, proposals/2021/Delete Energy cost reduction through rate adjustments - uncategorized.md, proposals/2021/Delete FutureOtherECMs.md, proposals/2021/Delete Install or Upgrade Master Venting.md, proposals/2021/Delete Separate SHW from heating.md
Reference issues #271, #272, #275
=> Remove redundant items

BuildingSync.xsd, proposals/2021/Change Cleaner Fuels to cleaner fuels.md
=> Correct capitalization - change `Convert to Cleaner Fuels` to `Convert to cleaner fuels`

README.md, docs/release_instructions.md
=> update links to buildingsync website

BuildingSync.xsd, proposals/2021/Add PRMS.md
Create proposal "Add PRMS.md"
Implement in schema
Resolves #381 for develop branch
=> Add PRMS in eGRIDRegionCode for develop branch

README.md, docs/release_instructions.md
We renamed the selection-tool repository which is now part of the general BuildingSync website.
Renamed https://github.com/buildingsync/selection-tool to https://github.com/buildingsync/buildingsync-website
n/a
n/a
=> renamed selection tool repo to website

BuildingSync.xsd, proposals/2021/Deprecate eGRIDRegionCode.md, translation/v2_to_v3.xsl
=> Deprecate eGRIDRegionCode

BuildingSync.xsd
See ticket
- points schemaLocation for gbXML to BSync's forked version
N/A
Closes #393
=> chore: point gbxml schemaLocation to BSync's fork

docs/notebooks/bsync_examples/Small-Office-Level-1.ipynb, docs/notebooks/bsync_examples/example1.xml, docs/notebooks/poetry.lock, docs/notebooks/pyproject.toml
The Jupyter notebook example was on version 2.3.
* Update to 2.4
* Update python dependencies in poetry.lock
* Run the jupyter notebook
#411
=> Use PyPi version of BSyncPy and Update to BuildingSync 2.4

BuildingSync.xsd, proposals/2021/Fix Implement hot aisle cold aisle design.md
=> Add Implement hot aisle cold aisle design

BuildingSync.xsd, proposals/2021/Deprecte Implement hot aisle hold aisle design.md
This is the follow-up change to #424 
Remove enumeration `Implement hot aisle hold aisle design` under element `auc:DataCenterImprovements`.
#420
=> Deprecate Implement hot aisle hold aisle design

BuildingSync.xsd
The root BuildingSync element has an `@version` attribute allowing users to specify the version of their document. We have been writing the full version, `MAJOR.MINOR.PATCH`, as the choices. This is not compatible with creating patch releases though -- since the `x.x.0` version was already released, it will consider any new patch version to be invalid according to that schema.
⚠️  From now on, we should _only_ add these `MAJOR.MINOR` versions!
- Use `MAJOR.MINOR` versions when specifying versions (but allow the old MAJOR.MINOR.PATCH to stick around)
#414
=> refactor: allow versions without PATCH included

BuildingSync.xsd
eGRID region code `MROE` was spelled incorrectly as `MORE` and this bug was fixed through #279 (adding the correct code) and #342 (deprecating the incorrect one in version 3.0). However the incorrect option was brought back while we refactor `eGRIDSubregionCode` in #387. We need to deprecate `MORE` again in version 3.0.
Remove `MORE` under `eGRIDSubregionCode`.
#431
=> Deprecate MORE in eGRIDSubregionCode

examples/ASHRAE 211 Export.xml
The ASHRAE 211 Export example file has the redundant `xmlns` and `nX:source` attributes in the interval reading elements. These should be removed to ease readability.
Remove the `xmlns` and `nX:source` attributes in the interval reading elements for v2 branch
#427
=> Update ASHRAE 211 Export example v2

examples/ASHRAE 211 Export.xml
The ASHRAE 211 Export example file has the redundant `xmlns` and `nX:source` attributes in the interval reading elements. These should be removed to ease readability.
Remove the `xmlns` and `nX:source` attributes in the interval reading elements for v3 branch
#427
=> Update ASHRAE 211 Export example v3

.gitignore, BuildingSync.xsd, docs/notebooks/example1-with-sensors.xml, proposals/2022/Add Emissions.md
Adding CO2e fields.
1. Added to AllResourceTotal: 
1. AnnualAverageCarbonEmissions
2. AnnualMarginalCarbonEmissions
2. Added to ResourceUse -> Emissions -> Emission:
1. EmissionsLinkedTimeSeriesIDs -> EmissionsLinkedTimeSeriesID
3. Added to TimeSeries -> TimeSeriesReadingQuantity
1. Enum "Emissions"
4. SCENARIO TYPES changes:
1. Added to ScenarioType -> CurrentBuilding:
1. Nothing
2. Added to ScenarioType -> Benchmark:
1. Nothing
3. Added to ScenarioType -> Target:
1. AnnualSavingsAverageCarbonEmissions
2. AnnualSavingsMarginalCarbonEmissions
4. Added to ScenarioType -> PackageOfMeasures:
1. AnnualSavingsAverageCarbonEmissions
2. AnnualSavingsMarginalCarbonEmissions
5. Added to ScenarioType -> Other:
1. AnnualSavingsAverageCarbonEmissions
2. AnnualSavingsMarginalCarbonEmissions
6. Added …
=> Schema modifications for CO2e

BuildingSync.xsd, proposals/2022/Add Equipment ID.md
N/A
New proposal to add "Equipment ID" field to the schema.
No testing required.
N/A
=> Create Add Equipment ID.md

BuildingSync.xsd, examples/AT_example_NYC_audit_report_property.xml, examples/AT_example_SF_audit_report.xml, examples/BuildingSync Website Invalid Schema.xml, examples/BuildingSync Website Valid Schema.xml, proposals/2022/Add DiscountRate.md
N/A
New proposal to add "Discount Rate" element.
N/A
N/A
=> Create Add DiscountRate.md

BuildingSync.xsd, proposals/2023/Add PrincipalLightingSystemType.md
See proposal
To add `PrincipalLightingSystemType` under `Building` and `Section` to enable direct mapping to/from Audit Template Tool, and omit the usage of UDF. However we do not recommend using this element other than AT use case, Instead, in BuildingSync world, we recommend using `System/LightingSystems/LightingSystem/LampType` to specify lighting type and link it to the correponding `Building` or `Section` via `LightingSystem/LinkedPremises`.
To do: need to confirm if the enumerations mapped correctly to AT library.
To do: need to make sure the usage of referencing global element is correct.
To do: test for schema and example validity.
#470
=> Add PrincipalLightingSystemType

BuildingSync.xsd, proposals/2023/Update PrincipalHVACSystemType.md
See proposal
Need to confirm the enumerations match Audit Template library.
#470
=> Change PrincipalHVACSystemType

BuildingSync.xsd, proposals/2023/Add AuditCycles.md
FEMP CERL use case
See proposal
#466
=> Add AuditCycles

BuildingSync.xsd, proposals/2023/Add FacilityEvaluationAuditDefinition.md
FEMP CERL use case
See proposal
#466
=> Add FacilityEvaluationAuditDefinition

BuildingSync.xsd, proposals/2023/Add WCM Categories.md
BuildingSync is adding water conservation measures (WCMs) into its measure library. Based on iterations of discussion and edits on the list of WCM categories and measure names in [here](https://docs.google.com/spreadsheets/d/15GUAZ6koG7dWHk_P00Gi-j43kdJReL7C/edit?usp=sharing&ouid=117281173110888138505&rtpof=true&sd=true), several new categories are proposed with associated measures, and other measures are distributed to existing corresponding BuildingSync measure categories. 
This PR is to add the new categories and associated measures.
[#165](https://github.com/BuildingSync/project-tracker/issues/165)
=> Add WCM categories

BuildingSync.xsd, proposals/2023/Add WCMs to existing Measure Categories.md
BuildingSync is adding water conservation measures (WCMs) into its measure library. Based on iterations of discussion and edits on the list of WCM categories and measure names in [here](https://docs.google.com/spreadsheets/d/15GUAZ6koG7dWHk_P00Gi-j43kdJReL7C/edit?usp=sharing&ouid=117281173110888138505&rtpof=true&sd=true), several new categories are proposed with associated measures, and other measures are distributed to existing corresponding BuildingSync measure categories. 
This PR is to add the new measures to existing BuildingSync measure categories.
[#165](https://github.com/BuildingSync/project-tracker/issues/165)
=> Add WCMs to existing categories

migration_scripts/README.md, migration_scripts/upgrade_from_2.4_to_2.5.py
Cute little script to modified BuildingSync files from 2.4 to 2.5
=> Make migrations scripts

BuildingSync.xsd, proposals/2024/Add LifeCycleSavings elements.md
=> Add Life Cycle Savings elements

docs/notebooks/bsync_examples/Primary-School-Levels1-2.md, docs/notebooks/bsync_examples/Reference-PrimarySchool-L100-Audit.xml, docs/notebooks/bsync_examples/Reference-PrimarySchool-L200-Audit.xml, docs/notebooks/bsync_examples/Small-Office-Level-1.md, docs/notebooks/bsync_examples/Small-Office-Level-2.md, docs/notebooks/bsync_examples/example-smalloffice-level1.xml, docs/notebooks/bsync_examples/example-smalloffice-level2.xml, docs/notebooks/example-with-emissions.xml, docs/notebooks/pyproject.toml, docs/release_instructions.md, examples/ASHRAE 211 Export.xml, examples/AT_example_AS_conversion_audit_report.xml, examples/AT_example_NYC_audit_report_property.xml, examples/AT_example_SF_audit_report.xml, examples/BuildingEQ-1.0.0.xml, examples/BuildingSync Website Invalid Schema.xml, examples/BuildingSync Website Valid Schema.xml, examples/CMS Woodlawn Campus.xml, examples/DC GSA Headquarters.xml, examples/Golden Test File.xml, examples/LL87.xml, examples/Multi-Facility Shared Systems.xml, examples/Multi_building_gbxml_externalreference_geometry.xml, examples/MultitenantBySubsections.xml, examples/NIST Gaithersburg Campus.xml, examples/Norfolk Federal Building.xml, examples/Reference Building - Primary School.xml, examples/Richmond Federal Building.xml, examples/Single_building_gbxml_externalreference_geometry.xml, migration_scripts/README.md
Update examples and docs to referencing BuildingSync 2.6
=> Update examples to 2.6

BuildingSync.xsd, proposals/2025/Add Optional Elements to All Assets.md
See proposal.
See proposal.
See proposal.
N/A
N/A
=> Proposal: Add Optional Elements to All Assets

BuildingSync.xsd, proposals/2025/Add Federal Fields.md
=> Proposal to add Federal building identifiers
